export const appliances = [
  { name: 'Amana', value: 'Amana' },
  { name: 'Forte', value: 'Forte' },
  { name: 'KitchenAid', value: 'KitchenAid' },
  { name: 'Monogram', value: 'Monogram' },
  { name: 'Bertazzoni', value: 'Bertazzoni' },
  { name: 'Frigidaire', value: 'Frigidaire' },
  { name: 'La Conue', value: 'La Conue' },
  { name: 'Smeg', value: 'Smeg' },
  { name: 'BlueStar', value: 'BlueStar' },
  { name: 'Gaggenau', value: 'Gaggenau' },
  { name: 'LG', value: 'LG' },
  { name: 'Sub-Zero', value: 'Sub-Zero' },
  { name: 'Bosch', value: 'Bosch' },
  { name: 'GE', value: 'GE' },
  { name: 'Liebherr', value: 'Liebherr' },
  { name: 'Thermador', value: 'Thermador' },
  { name: 'Cafe', value: 'Cafe' },
  { name: 'ILVE', value: 'ILVE' },
  { name: 'Maytag', value: 'Maytag' },
  { name: 'Viking', value: 'Viking' },
  { name: 'Dacor', value: 'Dacor' },
  { name: 'Jenn-Air', value: 'Jenn-Air' },
  { name: 'Miele', value: 'Miele' },
  { name: 'Wolf', value: 'Wolf' },
  { name: 'Fisher Paykel', value: 'Fisher Paykel' },
  { name: 'Haier', value: 'Haier' }
]

export const fixtures = [
  { name: 'Alfi', value: 'Alfi' },
  { name: 'Elkay', value: 'Elkay' },
  { name: 'Kohler', value: 'Kohler' },
  { name: 'Ruvati', value: 'Ruvati' },
  { name: 'Barclay', value: 'Barclay' },
  { name: 'Franke', value: 'Franke' },
  { name: 'KWC', value: 'KWC' },
  { name: 'Shaws', value: 'Shaws' },
  { name: 'Belwith-Keeler', value: 'Belwith-Keeler' },
  { name: 'Fresca', value: 'Fresca' },
  { name: 'Moen', value: 'Moen' },
  { name: 'Toto', value: 'Toto' },
  { name: 'Blanco', value: 'Blanco' },
  { name: 'Gado', value: 'Gado' },
  { name: 'Rohl', value: 'Rohl' },
  { name: 'Vigo', value: 'Vigo' },
  { name: 'Danze', value: 'Danze' },
  { name: 'Hansgrohe', value: 'Hansgrohe' },
  { name: 'Ronbow', value: 'Ronbow' },
  { name: 'Zen Designs', value: 'Zen Designs' },
  { name: 'Duravit', value: 'Duravit' },
  { name: 'Kingston Brass', value: 'Kingston Brass' }
]